### ISSUE TITLE
Use HTTPS to resolve Error: localhost didn’t send any data!

### ISSUE THREAD

**Issue by tanzil114** [toreini/DOMtegrity#1]
Maybe its obvious to some but it wasn't to me. I had a hard time running the app. Accessing localhost:8080 was giving this error:

localhost didn’t send any data.
ERR_EMPTY_RESPONSE

The solution is to use HTTPS (maybe because certificates are involved). So, in my case this did the trick:

**https://localhost:8080**

Thanks!

**Comment by toreini** [comment]
Hi Tanzil!

Thanks for the comment! It would help others as well.

Cheers,
Ehsan
